[project]
name = "epl-prediction-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nemo-code-ai", email = "themichaelugwumbanwoye@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.1",
]

[project.scripts]
epl-prediction-system = "epl_prediction_system:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
